name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.2+1
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  intl: ^0.16.0
  meta: ^1.1.7
  async: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: co.paystack.flutterpaystack
    pluginClass: FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=0.5.1 <2.0.0"